# Generate application log messages.
apiVersion: v1
kind: Namespace
metadata:
  name: chat
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: chat
    test: "true"
  name: chat-x
  namespace: chat
spec:
  containers:
  - name: chat
    image: quay.io/libpod/alpine
    command:
    - sh
    - "-c"
    - 'i=1; while true; do echo "$(date) chat says hello - $i"; i=$((i + 1)); sleep 1; done'
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      seccompProfile:
        type: "RuntimeDefault"
      capabilities:
        drop: [ALL]
