{
 "title": "Openshift Networking",
 "tags": [ "perfscale" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "_master_node",
    "label": "Master",
    "query": {
     "query": "label_values(kube_node_role{role=\"master\"}, node)"
    }
   },
   {
    "name": "_worker_node",
    "label": "Worker",
    "query": {
     "query": "label_values(kube_node_role{role=~\"work.*\"}, node)"
    }
   },
   {
    "name": "master_pod",
    "label": "OVNKube-Master",
    "query": {
     "query": "label_values({pod=~\"ovnkube-master.*\", namespace=~\"openshift-ovn-kubernetes\"}, pod)"
    }
   },
   {
    "name": "kubenode_pod",
    "label": "OVNKube-Node",
    "query": {
     "query": "label_values({pod=~\"ovnkube-node.*\", namespace=~\"openshift-ovn-kubernetes\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "OVN Resource Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "OVNKube Cluster Manager Leader",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "ovnkube_clustermanager_leader > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "OVN Northd Status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "ovn_northd_status", "legendFormat": "{{pod}}" }
     ]
    },
    {
     "title": "OVN Controller Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(ovn_controller_monitor_all) by (namespace)"
      }
     ]
    },
    {
     "title": "OVNKube Control Plane CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum( irate(container_cpu_usage_seconds_total{pod=~\"(ovnkube-master|ovnkube-control-plane).+\",namespace=\"openshift-ovn-kubernetes\",container!~\"POD|\"}[2m])*100 ) by (pod, node)",
       "legendFormat": "{{pod}} - {{node}}"
      }
     ]
    },
    {
     "title": "OVNKube Control Plane Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_rss{pod=~\"(ovnkube-master|ovnkube-control-plane).+\",namespace=\"openshift-ovn-kubernetes\",container!~\"POD|\"}",
       "legendFormat": "{{pod}} - {{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod Startup Latency Breakdown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scheduler Pod Scheduling Duration (P99)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(scheduler_pod_scheduling_sli_duration_seconds_bucket[5m])) > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Pod First Seen to LSP Created Latency (P99)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(ovnkube_controller_pod_first_seen_lsp_created_duration_seconds_bucket[2m])) by (pod, le)) > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Pod Annotation Latency (P99)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (pod, le) (rate(ovnkube_controller_pod_creation_latency_seconds_bucket[2m]))) > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Port Binding After LSP Creation Latency (P99)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(ovnkube_controller_pod_lsp_created_port_binding_duration_seconds_bucket[2m])) by (pod,le)) > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Port Binding to Chassis Assignment Latency (P99)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(ovnkube_controller_pod_port_binding_port_binding_chassis_duration_seconds_bucket[2m])) by (pod, le)) > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Port Marked As Up (P99)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(ovnkube_controller_pod_port_binding_chassis_port_binding_up_duration_seconds_bucket[2m])) by (pod, le)) > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CNI Request ADD Latency (P99)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(ovnkube_node_cni_request_duration_seconds_bucket{command=\"ADD\"}[2m])) by (pod,le)) > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Network Programming Complete (P99)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(ovnkube_controller_network_programming_duration_seconds_bucket[2m])) by (pod, le)) > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Sync Service Latency",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(ovnkube_master_sync_service_latency_seconds_sum[2m])",
       "legendFormat": "{{pod}} - Sync service latency"
      }
     ]
    },
    {
     "title": "OVNKube Node Ready Latency",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ovnkube_node_ready_duration_seconds{pod=~\"ovnkube-node-.*\",namespace=\"openshift-ovn-kubernetes\",container!~\"POD|\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "OVN Component Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "OVNKube Node Pods CPU Usage (Top 10)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "topk(10, (sum(irate(container_cpu_usage_seconds_total{name!=\"\",container!~\"POD|\",namespace=~\"openshift-ovn-kubernetes\", node=~\"$_worker_node\"}[2m]) * 100) by (pod, namespace, node)) > 0)",
       "legendFormat": "{{pod}} - {{node}}"
      }
     ]
    },
    {
     "title": "OVNKube Node Pods Memory Usage (Top 10)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(10, sum(container_memory_rss{name!=\"\",container!~\"POD|\",namespace=~\"openshift-ovn-kubernetes\", node=~\"$_worker_node\"}) by (pod, namespace, node))",
       "legendFormat": "{{pod}} - {{node}}"
      }
     ]
    },
    {
     "title": "Northd CPU Usage (Top 10)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "topk(10, sum(irate(container_cpu_usage_seconds_total{container=\"northd\", namespace=\"openshift-ovn-kubernetes\"}[2m])*100) by (pod, node))",
       "legendFormat": "{{pod}} - {{node}}"
      }
     ]
    },
    {
     "title": "Northd Memory Usage (Top 10)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(10, sum(container_memory_rss{container=\"northd\", namespace=\"openshift-ovn-kubernetes\"}) by (pod, node))",
       "legendFormat": "{{pod}} - {{node}}"
      }
     ]
    },
    {
     "title": "Sbdb CPU Usage (Top 10)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "topk(10, sum(irate(container_cpu_usage_seconds_total{container=\"sbdb\", namespace=\"openshift-ovn-kubernetes\"}[2m])*100) by (pod, node))",
       "legendFormat": "{{pod}} - {{node}}"
      }
     ]
    },
    {
     "title": "Sbdb Memory Usage (Top 10)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(10, sum(container_memory_rss{container=\"sbdb\", namespace=\"openshift-ovn-kubernetes\"}) by (pod, node))",
       "legendFormat": "{{pod}} - {{node}}"
      }
     ]
    },
    {
     "title": "Nbdb CPU Usage (Top 10)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "topk(10, sum(irate(container_cpu_usage_seconds_total{container=\"nbdb\", namespace=\"openshift-ovn-kubernetes\"}[2m])*100) by (pod, node))",
       "legendFormat": "{{pod}} - {{node}}"
      }
     ]
    },
    {
     "title": "Nbdb Memory Usage (Top 10)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(10, sum(container_memory_rss{container=\"nbdb\", namespace=\"openshift-ovn-kubernetes\"}) by (pod, node))",
       "legendFormat": "{{pod}} - {{node}}"
      }
     ]
    },
    {
     "title": "OVNKube Controller CPU Usage (Top 10)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "topk(10, sum(irate(container_cpu_usage_seconds_total{container=\"ovnkube-controller\", namespace=\"openshift-ovn-kubernetes\"}[2m])*100) by (pod, node))",
       "legendFormat": "{{pod}} - {{node}}"
      }
     ]
    },
    {
     "title": "OVNKube Controller Memory Usage (Top 10)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(10, sum(container_memory_rss{container=\"ovnkube-controller\", namespace=\"openshift-ovn-kubernetes\"}) by (pod, node))",
       "legendFormat": "{{pod}} - {{node}}"
      }
     ]
    },
    {
     "title": "OVN Controller CPU Usage (Top 10)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "topk(10, sum( irate(container_cpu_usage_seconds_total{pod=~\"ovnkube-.*\",namespace=\"openshift-ovn-kubernetes\",container=\"ovn-controller\"}[2m])*100)  by (pod,node) )",
       "legendFormat": "{{pod}} - {{node}}"
      }
     ]
    },
    {
     "title": "OVN Controller Memory Usage (Top 10)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(10, sum(container_memory_rss{pod=~\"ovnkube-node-.*\",namespace=\"openshift-ovn-kubernetes\",container=\"ovn-controller\"}) by (pod,node))",
       "legendFormat": "{{pod}} - {{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "WorkQueue Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "OVNKube Master workqueue",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(ovnkube_master_workqueue_adds_total[2m])",
       "legendFormat": "{{pod}} - Rate of handled adds"
      }
     ]
    },
    {
     "title": "OVNKube Master workqueue Depth",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "ovnkube_master_workqueue_depth", "legendFormat": "{{pod}} - Depth of workqueue" }
     ]
    },
    {
     "title": "OVNKube Master workqueue duration",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ovnkube_master_workqueue_longest_running_processor_seconds",
       "legendFormat": "{{pod}} - Longest processor duration"
      }
     ]
    },
    {
     "title": "OVNKube Master workqueue - Unfinished",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ovnkube_master_workqueue_unfinished_work_seconds",
       "legendFormat": "{{pod}} - Unfinished work duration"
      }
     ]
    }
   ]
  }
 ]
}