apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
  annotations:
    logging.openshift.io/preview-korrel8r-console: enabled # Enables korrel8r preview in openshift console
  name: instance
  namespace: openshift-logging
spec:
  managementState: Managed
  collection:
    type: vector
  logStore:
     type: lokistack
     lokistack:
       name: logging-loki
