# credit https://github.com/devonfw/devon4j/blob/develop/.github/workflows/github_actions.yml
name: github actions for development-tools
env:
  ORG: "observability-ui"
  REPO_SOURCE: "development-tools"
  REPO_DEST: "${REPO_SOURCE}.wiki"
  GH_REPO_SOURCE: "github.com/${ORG}/${REPO_SOURCE}.git"
  GH_REPO_DEST:  "github.com/${ORG}/${REPO_DEST}.git"
on:
  push:
    branches: [ main ]
jobs:
  include:
    runs-on: ubuntu-latest
    steps:
      - name: Documentation
        run: |
          cd ..
          git clone https://${GH_REPO_DEST}
          yes | cp -rf ${REPO_SOURCE}/docs/* ${REPO_DEST}/
          cd ${REPO_DEST}
          git config user.email ${EMAIL}
          git config user.name ${USER}
          git status
          git add .
          git commit -m "${REPO_SOURCE} docs | $(date +%s)"
          git remote add origin-wiki "https://${USER}:${GITHUB_TOKEN}@${GH_REPO_DEST}"
          git push origin-wiki master
